class StumpRunner {

	public static void main(String... values) {

		Stump stump1 = new Stump("whiteRock", "white", 40000, "Russia", true, 234567L, "glass fiber", 3.8, 3.0, 5.5);
		System.out.println("This is the first instance :");
		System.out.println("Brand :" + stump1.brand);
		System.out.println("color :" + stump1.color);
		System.out.println("cost :" + stump1.cost);
		System.out.println("origin :" + stump1.origin);
		System.out.println("camera :" + stump1.camera);
		System.out.println("id :" + stump1.id);
		System.out.println("material :" + stump1.material);
		System.out.println("weight :" + stump1.weight);
		System.out.println("length :" + stump1.length);
		System.out.println("sharpness :" + stump1.sharpness);
		System.out.println("\n");

		Stump stump2 = new Stump("StoneX", "gray", 42000, "India", false, 234568L, "carbon fiber", 3.5, 2.9, 5.0);
		System.out.println("This is the second instance :");
		System.out.println("Brand :" + stump2.brand);
		System.out.println("color :" + stump2.color);
		System.out.println("cost :" + stump2.cost);
		System.out.println("origin :" + stump2.origin);
		System.out.println("camera :" + stump2.camera);
		System.out.println("id :" + stump2.id);
		System.out.println("material :" + stump2.material);
		System.out.println("weight :" + stump2.weight);
		System.out.println("length :" + stump2.length);
		System.out.println("sharpness :" + stump2.sharpness);
		System.out.println("\n");

		Stump stump3 = new Stump("RockPro", "black", 46000, "USA", true, 234569L, "fiber", 4.2, 3.1, 5.8);
		System.out.println("This is the third instance :");
		System.out.println("Brand :" + stump3.brand);
		System.out.println("color :" + stump3.color);
		System.out.println("cost :" + stump3.cost);
		System.out.println("origin :" + stump3.origin);
		System.out.println("camera :" + stump3.camera);
		System.out.println("id :" + stump3.id);
		System.out.println("material :" + stump3.material);
		System.out.println("weight :" + stump3.weight);
		System.out.println("length :" + stump3.length);
		System.out.println("sharpness :" + stump3.sharpness);
		System.out.println("\n");

		Stump stump4 = new Stump("UltraStump", "blue", 38000, "UK", false, 234570L, "plastic", 3.0, 2.5, 4.5);
		System.out.println("This is the fourth instance :");
		System.out.println("Brand :" + stump4.brand);
		System.out.println("color :" + stump4.color);
		System.out.println("cost :" + stump4.cost);
		System.out.println("origin :" + stump4.origin);
		System.out.println("camera :" + stump4.camera);
		System.out.println("id :" + stump4.id);
		System.out.println("material :" + stump4.material);
		System.out.println("weight :" + stump4.weight);
		System.out.println("length :" + stump4.length);
		System.out.println("sharpness :" + stump4.sharpness);
		System.out.println("\n");

		Stump stump5 = new Stump("MegaCore", "red", 50000, "Germany", true, 234571L, "steel", 4.5, 3.2, 6.0);
		System.out.println("This is the fifth instance :");
		System.out.println("Brand :" + stump5.brand);
		System.out.println("color :" + stump5.color);
		System.out.println("cost :" + stump5.cost);
		System.out.println("origin :" + stump5.origin);
		System.out.println("camera :" + stump5.camera);
		System.out.println("id :" + stump5.id);
		System.out.println("material :" + stump5.material);
		System.out.println("weight :" + stump5.weight);
		System.out.println("length :" + stump5.length);
		System.out.println("sharpness :" + stump5.sharpness);
		System.out.println("\n");

		Stump stump6 = new Stump("HardEdge", "black", 47000, "Canada", true, 234572L, "fiber", 4.1, 3.0, 5.6);
		System.out.println("This is the Sixsth instance :");
		System.out.println("Brand :" + stump6.brand);
		System.out.println("color :" + stump6.color);
		System.out.println("cost :" + stump6.cost);
		System.out.println("origin :" + stump6.origin);
		System.out.println("camera :" + stump6.camera);
		System.out.println("id :" + stump6.id);
		System.out.println("material :" + stump6.material);
		System.out.println("weight :" + stump6.weight);
		System.out.println("length :" + stump6.length);
		System.out.println("sharpness :" + stump6.sharpness);
		System.out.println("\n");

		Stump stump7 = new Stump("CoreMax", "white", 41000, "France", false, 234573L, "glass", 3.6, 2.8, 5.1);
		System.out.println("This is the seventh instance :");
		System.out.println("Brand :" + stump7.brand);
		System.out.println("color :" + stump7.color);
		System.out.println("cost :" + stump7.cost);
		System.out.println("origin :" + stump7.origin);
		System.out.println("camera :" + stump7.camera);
		System.out.println("id :" + stump7.id);
		System.out.println("material :" + stump7.material);
		System.out.println("weight :" + stump7.weight);
		System.out.println("length :" + stump7.length);
		System.out.println("sharpness :" + stump7.sharpness);
		System.out.println("\n");

		Stump stump8 = new Stump("AlphaStump", "green", 39000, "Italy", true, 234574L, "carbon fiber", 3.7, 2.7, 5.2);
		System.out.println("This is the eighth instance :");
		System.out.println("Brand :" + stump8.brand);
		System.out.println("color :" + stump8.color);
		System.out.println("cost :" + stump8.cost);
		System.out.println("origin :" + stump8.origin);
		System.out.println("camera :" + stump8.camera);
		System.out.println("id :" + stump8.id);
		System.out.println("material :" + stump8.material);
		System.out.println("weight :" + stump8.weight);
		System.out.println("length :" + stump8.length);
		System.out.println("sharpness :" + stump8.sharpness);
		System.out.println("\n");

		Stump stump9 = new Stump("StrongBase", "yellow", 43000, "Spain", false, 234575L, "fiber", 3.9, 3.0, 5.3);
		System.out.println("This is the ninth instance :");
		System.out.println("Brand :" + stump9.brand);
		System.out.println("color :" + stump9.color);
		System.out.println("cost :" + stump9.cost);
		System.out.println("origin :" + stump9.origin);
		System.out.println("camera :" + stump9.camera);
		System.out.println("id :" + stump9.id);
		System.out.println("material :" + stump9.material);
		System.out.println("weight :" + stump9.weight);
		System.out.println("length :" + stump9.length);
		System.out.println("sharpness :" + stump9.sharpness);
		System.out.println("\n");

		Stump stump10 = new Stump("EdgePro", "black", 48000, "USA", true, 234576L, "steel", 4.3, 3.3, 6.2);
		System.out.println("This is the tenth instance :");
		System.out.println("Brand :" + stump10.brand);
		System.out.println("color :" + stump10.color);
		System.out.println("cost :" + stump10.cost);
		System.out.println("origin :" + stump10.origin);
		System.out.println("camera :" + stump10.camera);
		System.out.println("id :" + stump10.id);
		System.out.println("material :" + stump10.material);
		System.out.println("weight :" + stump10.weight);
		System.out.println("length :" + stump10.length);
		System.out.println("sharpness :" + stump10.sharpness);
		System.out.println("\n");

		Stump stump11 = new Stump("RockSolid", "gray", 45000, "India", false, 234577L, "plastic", 3.4, 2.6, 4.8);
		System.out.println("This is the 11th instance :");
		System.out.println("Brand :" + stump11.brand);
		System.out.println("color :" + stump11.color);
		System.out.println("cost :" + stump11.cost);
		System.out.println("origin :" + stump11.origin);
		System.out.println("camera :" + stump11.camera);
		System.out.println("id :" + stump11.id);
		System.out.println("material :" + stump11.material);
		System.out.println("weight :" + stump11.weight);
		System.out.println("length :" + stump11.length);
		System.out.println("sharpness :" + stump11.sharpness);
		System.out.println("\n");

		Stump stump12 = new Stump("TitanCore", "silver", 52000, "Japan", true, 234578L, "titanium", 4.6, 3.4, 6.5);
		System.out.println("This is the 12th instance :");
		System.out.println("Brand :" + stump12.brand);
		System.out.println("color :" + stump12.color);
		System.out.println("cost :" + stump12.cost);
		System.out.println("origin :" + stump12.origin);
		System.out.println("camera :" + stump12.camera);
		System.out.println("id :" + stump12.id);
		System.out.println("material :" + stump12.material);
		System.out.println("weight :" + stump12.weight);
		System.out.println("length :" + stump12.length);
		System.out.println("sharpness :" + stump12.sharpness);
		System.out.println("\n");

		Stump stump13 = new Stump("FlexiStump", "orange", 37000, "China", false, 234579L, "rubber", 3.2, 2.5, 4.2);
		System.out.println("This is the 13th instance :");
		System.out.println("Brand :" + stump13.brand);
		System.out.println("color :" + stump13.color);
		System.out.println("cost :" + stump13.cost);
		System.out.println("origin :" + stump13.origin);
		System.out.println("camera :" + stump13.camera);
		System.out.println("id :" + stump13.id);
		System.out.println("material :" + stump13.material);
		System.out.println("weight :" + stump13.weight);
		System.out.println("length :" + stump13.length);
		System.out.println("sharpness :" + stump13.sharpness);
		System.out.println("\n");

		Stump stump14 = new Stump("MaxGrip", "black", 46000, "Korea", true, 234580L, "fiber", 4.0, 3.0, 5.7);
		System.out.println("This is the 14 instance :");
		System.out.println("Brand :" + stump14.brand);
		System.out.println("color :" + stump14.color);
		System.out.println("cost :" + stump14.cost);
		System.out.println("origin :" + stump14.origin);
		System.out.println("camera :" + stump14.camera);
		System.out.println("id :" + stump14.id);
		System.out.println("material :" + stump14.material);
		System.out.println("weight :" + stump14.weight);
		System.out.println("length :" + stump14.length);
		System.out.println("sharpness :" + stump14.sharpness);
		System.out.println("\n");

		Stump stump15 = new Stump("CoreLite", "white", 39000, "Brazil", false, 234581L, "plastic", 3.3, 2.7, 4.9);
		System.out.println("This is the 15th instance :");
		System.out.println("Brand :" + stump15.brand);
		System.out.println("color :" + stump15.color);
		System.out.println("cost :" + stump15.cost);
		System.out.println("origin :" + stump15.origin);
		System.out.println("camera :" + stump15.camera);
		System.out.println("id :" + stump15.id);
		System.out.println("material :" + stump15.material);
		System.out.println("weight :" + stump15.weight);
		System.out.println("length :" + stump15.length);
		System.out.println("sharpness :" + stump15.sharpness);
		System.out.println("\n");

		Stump stump16 = new Stump("PowerStump", "red", 51000, "Germany", true, 234582L, "steel", 4.7, 3.5, 6.3);
		System.out.println("This is the 16th instance :");
		System.out.println("Brand :" + stump16.brand);
		System.out.println("color :" + stump16.color);
		System.out.println("cost :" + stump16.cost);
		System.out.println("origin :" + stump16.origin);
		System.out.println("camera :" + stump16.camera);
		System.out.println("id :" + stump16.id);
		System.out.println("material :" + stump16.material);
		System.out.println("weight :" + stump16.weight);
		System.out.println("length :" + stump16.length);
		System.out.println("sharpness :" + stump16.sharpness);
		System.out.println("\n");

		Stump stump17 = new Stump("EdgeLite", "blue", 40000, "UK", false, 234583L, "glass fiber", 3.5, 2.8, 5.0);
		System.out.println("This is the 17th instance :");
		System.out.println("Brand :" + stump17.brand);
		System.out.println("color :" + stump17.color);
		System.out.println("cost :" + stump17.cost);
		System.out.println("origin :" + stump17.origin);
		System.out.println("camera :" + stump17.camera);
		System.out.println("id :" + stump17.id);
		System.out.println("material :" + stump17.material);
		System.out.println("weight :" + stump17.weight);
		System.out.println("length :" + stump17.length);
		System.out.println("sharpness :" + stump17.sharpness);
		System.out.println("\n");

		Stump stump18 = new Stump("UltraCore", "black", 48000, "USA", true, 234584L, "carbon fiber", 4.2, 3.1, 5.9);
		System.out.println("This is the 18th instance :");
		System.out.println("Brand :" + stump18.brand);
		System.out.println("color :" + stump18.color);
		System.out.println("cost :" + stump18.cost);
		System.out.println("origin :" + stump18.origin);
		System.out.println("camera :" + stump18.camera);
		System.out.println("id :" + stump18.id);
		System.out.println("material :" + stump18.material);
		System.out.println("weight :" + stump18.weight);
		System.out.println("length :" + stump18.length);
		System.out.println("sharpness :" + stump18.sharpness);
		System.out.println("\n");

		Stump stump19 = new Stump("BasePro", "gray", 42000, "India", false, 234585L, "fiber", 3.6, 2.9, 5.1);
		System.out.println("This is the 19th instance :");
		System.out.println("Brand :" + stump19.brand);
		System.out.println("color :" + stump19.color);
		System.out.println("cost :" + stump19.cost);
		System.out.println("origin :" + stump19.origin);
		System.out.println("camera :" + stump19.camera);
		System.out.println("id :" + stump19.id);
		System.out.println("material :" + stump19.material);
		System.out.println("weight :" + stump19.weight);
		System.out.println("length :" + stump19.length);
		System.out.println("sharpness :" + stump19.sharpness);
		System.out.println("\n");

		Stump stump20 = new Stump("SteelEdge", "silver", 53000, "Japan", true, 234586L, "steel", 4.8, 3.6, 6.6);
		System.out.println("This is the 20th instance :");
		System.out.println("Brand :" + stump20.brand);
		System.out.println("color :" + stump20.color);
		System.out.println("cost :" + stump20.cost);
		System.out.println("origin :" + stump20.origin);
		System.out.println("camera :" + stump20.camera);
		System.out.println("id :" + stump20.id);
		System.out.println("material :" + stump20.material);
		System.out.println("weight :" + stump20.weight);
		System.out.println("length :" + stump20.length);
		System.out.println("sharpness :" + stump20.sharpness);
		System.out.println("\n");

		Stump stump21 = new Stump("GripMax", "green", 39000, "Italy", false, 234587L, "rubber", 3.4, 2.7, 4.7);
		System.out.println("This is the 21st instance :");
		System.out.println("Brand :" + stump21.brand);
		System.out.println("color :" + stump21.color);
		System.out.println("cost :" + stump21.cost);
		System.out.println("origin :" + stump21.origin);
		System.out.println("camera :" + stump21.camera);
		System.out.println("id :" + stump21.id);
		System.out.println("material :" + stump21.material);
		System.out.println("weight :" + stump21.weight);
		System.out.println("length :" + stump21.length);
		System.out.println("sharpness :" + stump21.sharpness);
		System.out.println("\n");

		Stump stump22 = new Stump("CoreSteel", "black", 47000, "USA", true, 234588L, "steel", 4.3, 3.2, 6.1);
		System.out.println("This is the 22nd instance :");
		System.out.println("Brand :" + stump22.brand);
		System.out.println("color :" + stump22.color);
		System.out.println("cost :" + stump22.cost);
		System.out.println("origin :" + stump22.origin);
		System.out.println("camera :" + stump22.camera);
		System.out.println("id :" + stump22.id);
		System.out.println("material :" + stump22.material);
		System.out.println("weight :" + stump22.weight);
		System.out.println("length :" + stump22.length);
		System.out.println("sharpness :" + stump22.sharpness);
		System.out.println("\n");

		Stump stump23 = new Stump("FlexCore", "white", 41000, "France", false, 234589L, "plastic", 3.5, 2.8, 5.0);
		System.out.println("This is the 23rd instance :");
		System.out.println("Brand :" + stump23.brand);
		System.out.println("color :" + stump23.color);
		System.out.println("cost :" + stump23.cost);
		System.out.println("origin :" + stump23.origin);
		System.out.println("camera :" + stump23.camera);
		System.out.println("id :" + stump23.id);
		System.out.println("material :" + stump23.material);
		System.out.println("weight :" + stump23.weight);
		System.out.println("length :" + stump23.length);
		System.out.println("sharpness :" + stump23.sharpness);
		System.out.println("\n");

		Stump stump24 = new Stump("RockEdge", "gray", 44000, "Spain", true, 234590L, "fiber", 3.9, 3.0, 5.4);
		System.out.println("This is the 24th instance :");
		System.out.println("Brand :" + stump24.brand);
		System.out.println("color :" + stump24.color);
		System.out.println("cost :" + stump24.cost);
		System.out.println("origin :" + stump24.origin);
		System.out.println("camera :" + stump24.camera);
		System.out.println("id :" + stump24.id);
		System.out.println("material :" + stump24.material);
		System.out.println("weight :" + stump24.weight);
		System.out.println("length :" + stump24.length);
		System.out.println("sharpness :" + stump24.sharpness);
		System.out.println("\n");

		Stump stump25 = new Stump("UltraGrip", "black", 50000, "Canada", true, 234591L, "carbon fiber", 4.5, 3.3, 6.2);
		System.out.println("This is the 25th instance :");
		System.out.println("Brand :" + stump25.brand);
		System.out.println("color :" + stump25.color);
		System.out.println("cost :" + stump25.cost);
		System.out.println("origin :" + stump25.origin);
		System.out.println("camera :" + stump25.camera);
		System.out.println("id :" + stump25.id);
		System.out.println("material :" + stump25.material);
		System.out.println("weight :" + stump25.weight);
		System.out.println("length :" + stump25.length);
		System.out.println("sharpness :" + stump25.sharpness);
		System.out.println("\n");
	}
}