package com.xworkz.devcollections.linkedlist.countryInfo;

import com.xworkz.devcollections.linkedlist.countryInfo.constant.Continent;
import com.xworkz.devcollections.linkedlist.countryInfo.dto.CountryDto;

import java.util.LinkedList;
import java.util.List;

public class CountryRunner {


        public static void main(String[] args) {
            CountryDto country1 = new CountryDto(1, "Afghanistan", "Hasan Akhund", Continent.ASIA, 230L, 652230.0, 34, "AF");
            CountryDto country2 = new CountryDto(2, "Albania", "Edi Rama", Continent.EUROPE, 90L, 28748.0, 12, "AL");
            CountryDto country3 = new CountryDto(3, "Algeria", "Nadir Larbaoui", Continent.AFRICA, 310L, 2381741.0, 58, "DZ");
            CountryDto country4 = new CountryDto(4, "Andorra", "Xavier Espot", Continent.EUROPE, 18L, 468.0, 7, "AD");
            CountryDto country5 = new CountryDto(5, "Angola", "Manuel Homem", Continent.AFRICA, 185L, 1246700.0, 18, "AO");
            CountryDto country6 = new CountryDto(6, "Antigua and Barbuda", "Gaston Browne", Continent.NORTH_AMERICA, 15L, 442.0, 6, "AG");
            CountryDto country7 = new CountryDto(7, "Argentina", "Guillermo Francos", Continent.SOUTH_AMERICA, 245L, 2780400.0, 23, "AR");
            CountryDto country8 = new CountryDto(8, "Armenia", "Nikol Pashinyan", Continent.ASIA, 95L, 29743.0, 11, "AM");
            CountryDto country9 = new CountryDto(9, "Australia", "Anthony Albanese", Continent.AUSTRALIA, 170L, 7692024.0, 6, "AU");
            CountryDto country10 = new CountryDto(10, "Austria", "Christian Stocker", Continent.EUROPE, 85L, 83879.0, 9, "AT");
            CountryDto country11 = new CountryDto(11, "Azerbaijan", "Ali Asadov", Continent.ASIA, 155L, 86600.0, 66, "AZ");
            CountryDto country12 = new CountryDto(12, "Bahamas", "Philip Davis", Continent.NORTH_AMERICA, 20L, 13943.0, 32, "BS");
            CountryDto country13 = new CountryDto(13, "Bahrain", "Salman bin Hamad Al Khalifa", Continent.ASIA, 120L, 765.0, 4, "BH");
            CountryDto country14 = new CountryDto(14, "Bangladesh", "Muhammad Yunus", Continent.ASIA, 410L, 148460.0, 8, "BD");
            CountryDto country15 = new CountryDto(15, "Barbados", "Mia Mottley", Continent.NORTH_AMERICA, 12L, 430.0, 11, "BB");
            CountryDto country16 = new CountryDto(16, "Belarus", "Alexander Turchin", Continent.EUROPE, 125L, 207600.0, 6, "BY");
            CountryDto country17 = new CountryDto(17, "Belgium", "Bart De Wever", Continent.EUROPE, 98L, 30528.0, 10, "BE");
            CountryDto country18 = new CountryDto(18, "Belize", "John Briceño", Continent.NORTH_AMERICA, 26L, 22966.0, 6, "BZ");
            CountryDto country19 = new CountryDto(19, "Benin", "Patrice Talon", Continent.AFRICA, 82L, 114763.0, 12, "BJ");
            CountryDto country20 = new CountryDto(20, "Bhutan", "Tshering Tobgay", Continent.ASIA, 10L, 38394.0, 20, "BT");
            CountryDto country21 = new CountryDto(21, "Bolivia", "Luis Arce", Continent.SOUTH_AMERICA, 135L, 1098581.0, 9, "BO");
            CountryDto country22 = new CountryDto(22, "Bosnia and Herzegovina", "Borjana Kristo", Continent.EUROPE, 65L, 51197.0, 2, "BA");
            CountryDto country23 = new CountryDto(23, "Botswana", "Duma Boko", Continent.AFRICA, 42L, 581730.0, 10, "BW");
            CountryDto country24 = new CountryDto(24, "Brazil", "Luiz Inácio Lula da Silva", Continent.SOUTH_AMERICA, 340L, 8515767.0, 26, "BR");
            CountryDto country25 = new CountryDto(25, "Brunei", "Sultan Hassanal Bolkiah", Continent.ASIA, 30L, 5765.0, 4, "BN");
            CountryDto country26 = new CountryDto(26, "Bulgaria", "Rossen Jeliazkov", Continent.EUROPE, 92L, 110994.0, 28, "BG");
            CountryDto country27 = new CountryDto(27, "Burkina Faso", "Jean Emmanuel Ouédraogo", Continent.AFRICA, 75L, 274223.0, 13, "BF");
            CountryDto country28 = new CountryDto(28, "Burundi", "Gervais Ndirakobuca", Continent.AFRICA, 45L, 27834.0, 18, "BI");
            CountryDto country29 = new CountryDto(29, "Cabo Verde", "Ulisses Correia e Silva", Continent.AFRICA, 15L, 4033.0, 22, "CV");
            CountryDto country30 = new CountryDto(30, "Cambodia", "Hun Manet", Continent.ASIA, 140L, 181035.0, 25, "KH");
            CountryDto country31 = new CountryDto(31, "Cameroon", "Joseph Dion Ngute", Continent.AFRICA, 170L, 475442.0, 10, "CM");
            CountryDto country32 = new CountryDto(32, "Canada", "Mark Carney", Continent.NORTH_AMERICA, 150L, 9984670.0, 10, "CA");
            CountryDto country33 = new CountryDto(33, "Central African Republic", "Félix Moloua", Continent.AFRICA, 55L, 622984.0, 16, "CF");
            CountryDto country34 = new CountryDto(34, "Chad", "Allamaye Halina", Continent.AFRICA, 70L, 1284000.0, 23, "TD");
            CountryDto country35 = new CountryDto(35, "Chile", "Gabriel Boric", Continent.SOUTH_AMERICA, 110L, 756102.0, 16, "CL");
            CountryDto country36 = new CountryDto(36, "China", "Li Qiang", Continent.ASIA, 900L, 9596961.0, 34, "CN");
            CountryDto country37 = new CountryDto(37, "Colombia", "Gustavo Petro", Continent.SOUTH_AMERICA, 180L, 1141748.0, 32, "CO");
            CountryDto country38 = new CountryDto(38, "Comoros", "Azali Assoumani", Continent.AFRICA, 18L, 2235.0, 3, "KM");
            CountryDto country39 = new CountryDto(39, "Congo", "Anatole Collinet Makosso", Continent.AFRICA, 90L, 342000.0, 12, "CG");
            CountryDto country40 = new CountryDto(40, "Costa Rica", "Rodrigo Chaves Robles", Continent.NORTH_AMERICA, 35L, 51100.0, 7, "CR");
            CountryDto country41 = new CountryDto(41, "Croatia", "Andrej Plenković", Continent.EUROPE, 60L, 56594.0, 20, "HR");
            CountryDto country42 = new CountryDto(42, "Cuba", "Manuel Marrero Cruz", Continent.NORTH_AMERICA, 75L, 109884.0, 15, "CU");
            CountryDto country43 = new CountryDto(43, "Cyprus", "Nikos Christodoulides", Continent.ASIA, 45L, 9251.0, 6, "CY");
            CountryDto country44 = new CountryDto(44, "Czech Republic", "Petr Fiala", Continent.EUROPE, 82L, 78871.0, 14, "CZ");
            CountryDto country45 = new CountryDto(45, "Democratic Republic of the Congo", "Judith Suminwa", Continent.AFRICA, 220L, 2344858.0, 26, "CD");
            CountryDto country46 = new CountryDto(46, "Denmark", "Mette Frederiksen", Continent.EUROPE, 40L, 42933.0, 5, "DK");
            CountryDto country47 = new CountryDto(47, "Djibouti", "Abdoulkader Kamil Mohamed", Continent.AFRICA, 22L, 23200.0, 6, "DJ");
            CountryDto country48 = new CountryDto(48, "Dominica", "Roosevelt Skerrit", Continent.NORTH_AMERICA, 8L, 751.0, 10, "DM");
            CountryDto country49 = new CountryDto(49, "Dominican Republic", "Luis Abinader", Continent.NORTH_AMERICA, 88L, 48671.0, 31, "DO");
            CountryDto country50 = new CountryDto(50, "Ecuador", "Daniel Noboa", Continent.SOUTH_AMERICA, 120L, 276841.0, 24, "EC");
            CountryDto country51 = new CountryDto(51, "Egypt", "Mostafa Madbouly", Continent.AFRICA, 420L, 1002450.0, 27, "EG");
            CountryDto country52 = new CountryDto(52, "El Salvador", "Nayib Bukele", Continent.NORTH_AMERICA, 60L, 21041.0, 14, "SV");
            CountryDto country53 = new CountryDto(53, "Equatorial Guinea", "Manuela Roka Botey", Continent.AFRICA, 30L, 28051.0, 8, "GQ");
            CountryDto country54 = new CountryDto(54, "Eritrea", "Osman Saleh", Continent.AFRICA, 35L, 117600.0, 6, "ER");
            CountryDto country55 = new CountryDto(55, "Estonia", "Kristen Michal", Continent.EUROPE, 25L, 45227.0, 15, "EE");
            CountryDto country56 = new CountryDto(56, "Eswatini", "Russell Dlamini", Continent.AFRICA, 18L, 17364.0, 4, "SZ");
            CountryDto country57 = new CountryDto(57, "Ethiopia", "Abiy Ahmed", Continent.AFRICA, 260L, 1104300.0, 12, "ET");
            CountryDto country58 = new CountryDto(58, "Fiji", "Sitiveni Rabuka", Continent.AUSTRALIA, 15L, 18274.0, 4, "FJ");
            CountryDto country59 = new CountryDto(59, "Finland", "Petteri Orpo", Continent.EUROPE, 20L, 338455.0, 19, "FI");
            CountryDto country60 = new CountryDto(60, "France", "François Bayrou", Continent.EUROPE, 150L, 551695.0, 18, "FR");
            CountryDto country61 = new CountryDto(61, "Gabon", "Raymond Ndong Sima", Continent.AFRICA, 40L, 267668.0, 9, "GA");
            CountryDto country62 = new CountryDto(62, "Gambia", "Muhammed B. S. Jallow", Continent.AFRICA, 15L, 11295.0, 6, "GM");
            CountryDto country63 = new CountryDto(63, "Georgia", "Irakli Kobakhidze", Continent.ASIA, 70L, 69700.0, 9, "GE");
            CountryDto country64 = new CountryDto(64, "Germany", "Friedrich Merz", Continent.EUROPE, 180L, 357588.0, 16, "DE");
            CountryDto country65 = new CountryDto(65, "Ghana", "John Dramani Mahama", Continent.AFRICA, 90L, 238533.0, 16, "GH");
            CountryDto country66 = new CountryDto(66, "Greece", "Kyriakos Mitsotakis", Continent.EUROPE, 85L, 131957.0, 13, "GR");
            CountryDto country67 = new CountryDto(67, "Grenada", "Dickon Mitchell", Continent.NORTH_AMERICA, 8L, 348.0, 6, "GD");
            CountryDto country68 = new CountryDto(68, "Guatemala", "Bernardo Arévalo", Continent.NORTH_AMERICA, 70L, 108889.0, 22, "GT");
            CountryDto country69 = new CountryDto(69, "Guinea", "Bah Oury", Continent.AFRICA, 80L, 245857.0, 8, "GN");
            CountryDto country70 = new CountryDto(70, "Guinea-Bissau", "Rui Duarte de Barros", Continent.AFRICA, 20L, 36125.0, 9, "GW");
            CountryDto country71 = new CountryDto(71, "Guyana", "Mark Phillips", Continent.SOUTH_AMERICA, 22L, 214969.0, 10, "GY");
            CountryDto country72 = new CountryDto(72, "Haiti", "Alix Didier Fils-Aimé", Continent.NORTH_AMERICA, 40L, 27750.0, 10, "HT");
            CountryDto country73 = new CountryDto(73, "Honduras", "Xiomara Castro", Continent.NORTH_AMERICA, 65L, 112492.0, 18, "HN");
            CountryDto country74 = new CountryDto(74, "Hungary", "Viktor Orbán", Continent.EUROPE, 90L, 93028.0, 19, "HU");
            CountryDto country75 = new CountryDto(75, "Iceland", "Kristrún Frostadóttir", Continent.EUROPE, 8L, 103000.0, 8, "IS");
            CountryDto country76 = new CountryDto(76, "India", "Narendra Modi", Continent.ASIA, 950L, 3287263.0, 28, "IN");
            CountryDto country77 = new CountryDto(77, "Indonesia", "Prabowo Subianto", Continent.ASIA, 500L, 1904569.0, 38, "ID");
            CountryDto country78 = new CountryDto(78, "Iran", "Masoud Pezeshkian", Continent.ASIA, 420L, 1648195.0, 31, "IR");
            CountryDto country79 = new CountryDto(79, "Iraq", "Mohammed Shia' Al Sudani", Continent.ASIA, 310L, 438317.0, 19, "IQ");
            CountryDto country80 = new CountryDto(80, "Ireland", "Micheál Martin", Continent.EUROPE, 35L, 70273.0, 26, "IE");
            CountryDto country81 = new CountryDto(81, "Israel", "Benjamin Netanyahu", Continent.ASIA, 100L, 22145.0, 6, "IL");
            CountryDto country82 = new CountryDto(82, "Italy", "Giorgia Meloni", Continent.EUROPE, 170L, 301340.0, 20, "IT");
            CountryDto country83 = new CountryDto(83, "Ivory Coast", "Robert Beugré Mambé", Continent.AFRICA, 95L, 322463.0, 14, "CI");
            CountryDto country84 = new CountryDto(84, "Jamaica", "Andrew Holness", Continent.NORTH_AMERICA, 30L, 10991.0, 14, "JM");
            CountryDto country85 = new CountryDto(85, "Japan", "Shigeru Ishiba", Continent.ASIA, 190L, 377975.0, 47, "JP");
            CountryDto country86 = new CountryDto(86, "Jordan", "Jafar Hassan", Continent.ASIA, 75L, 89342.0, 12, "JO");
            CountryDto country87 = new CountryDto(87, "Kazakhstan", "Olzhas Bektenov", Continent.ASIA, 210L, 2724900.0, 17, "KZ");
            CountryDto country88 = new CountryDto(88, "Kenya", "Musalia Mudavadi", Continent.AFRICA, 180L, 580367.0, 47, "KE");
            CountryDto country89 = new CountryDto(89, "Kiribati", "Taneti Maamau", Continent.AUSTRALIA, 5L, 811.0, 3, "KI");
            CountryDto country90 = new CountryDto(90, "Kuwait", "Ahmad Abdullah Al Ahmad Al Sabah", Continent.ASIA, 110L, 17818.0, 6, "KW");
            CountryDto country91 = new CountryDto(91, "Kyrgyzstan", "Adylbek Kasymaliev", Continent.ASIA, 65L, 199951.0, 7, "KG");
            CountryDto country92 = new CountryDto(92, "Laos", "Sonexay Siphandone", Continent.ASIA, 55L, 236800.0, 18, "LA");
            CountryDto country93 = new CountryDto(93, "Latvia", "Evika Siliņa", Continent.EUROPE, 28L, 64589.0, 43, "LV");
            CountryDto country94 = new CountryDto(94, "Lebanon", "Nawaf Salam", Continent.ASIA, 60L, 10452.0, 8, "LB");
            CountryDto country95 = new CountryDto(95, "Lesotho", "Sam Matekane", Continent.AFRICA, 15L, 30355.0, 10, "LS");
            CountryDto country96 = new CountryDto(96, "Liberia", "Joseph Boakai", Continent.AFRICA, 35L, 111369.0, 15, "LR");
            CountryDto country97 = new CountryDto(97, "Libya", "Abdul Hamid Dbeibeh", Continent.AFRICA, 140L, 1759540.0, 22, "LY");
            CountryDto country98 = new CountryDto(98, "Liechtenstein", "Daniel Risch", Continent.EUROPE, 5L, 160.0, 11, "LI");
            CountryDto country99 = new CountryDto(99, "Lithuania", "Gintautas Paluckas", Continent.EUROPE, 32L, 65300.0, 60, "LT");
            CountryDto country100 = new CountryDto(100, "Luxembourg", "Luc Frieden", Continent.EUROPE, 12L, 2586.0, 12, "LU");
            CountryDto country101 = new CountryDto(101, "Madagascar", "Christian Ntsay", Continent.AFRICA, 55L, 587041d, 23, "MG");
            CountryDto country102 = new CountryDto(102, "Malawi", "Lazarus Chakwera", Continent.AFRICA, 42L, 118484d, 28, "MW");
            CountryDto country103 = new CountryDto(103, "Malaysia", "Anwar Ibrahim", Continent.ASIA, 180L, 330803d, 13, "MY");
            CountryDto country104 = new CountryDto(104, "Maldives", "Mohamed Muizzu", Continent.ASIA, 10L, 300d, 20, "MV");
            CountryDto country105 = new CountryDto(105, "Mali", "Abdoulaye Maïga", Continent.AFRICA, 75L, 1240192d, 10, "ML");
            CountryDto country106 = new CountryDto(106, "Malta", "Robert Abela", Continent.EUROPE, 12L, 316d, 5, "MT");
            CountryDto country107 = new CountryDto(107, "Marshall Islands", "Hilda Heine", Continent.AUSTRALIA, 5L, 181d, 24, "MH");
            CountryDto country108 = new CountryDto(108, "Mauritania", "Mokhtar Ould Diay", Continent.AFRICA, 40L, 1030700d, 15, "MR");
            CountryDto country109 = new CountryDto(109, "Mauritius", "Navin Ramgoolam", Continent.AFRICA, 15L, 2040d, 9, "MU");
            CountryDto country110 = new CountryDto(110, "Mexico", "Claudia Sheinbaum", Continent.NORTH_AMERICA, 350L, 1964375d, 32, "MX");
            CountryDto country111 = new CountryDto(111, "Micronesia", "Wesley Simina", Continent.AUSTRALIA, 5L, 702d, 4, "FM");
            CountryDto country112 = new CountryDto(112, "Moldova", "Dorin Recean", Continent.EUROPE, 35L, 33846d, 32, "MD");
            CountryDto country113 = new CountryDto(113, "Monaco", "Pierre Dartout", Continent.EUROPE, 4L, 2.02d, 1, "MC");
            CountryDto country114 = new CountryDto(114, "Mongolia", "Luvsannamsrain Oyun-Erdene", Continent.ASIA, 60L, 1564116d, 21, "MN");
            CountryDto country115 = new CountryDto(115, "Montenegro", "Milojko Spajić", Continent.EUROPE, 18L, 13812d, 25, "ME");
            CountryDto country116 = new CountryDto(116, "Morocco", "Aziz Akhannouch", Continent.AFRICA, 120L, 446550d, 12, "MA");
            CountryDto country117 = new CountryDto(117, "Mozambique", "Maria Benvinda Levy", Continent.AFRICA, 95L, 801590d, 11, "MZ");
            CountryDto country118 = new CountryDto(118, "Myanmar", "Min Aung Hlaing", Continent.ASIA, 210L, 676578d, 14, "MM");
            CountryDto country119 = new CountryDto(119, "Namibia", "Elijah Ngurare", Continent.AFRICA, 28L, 825615d, 14, "NA");
            CountryDto country120 = new CountryDto(120, "Nauru", "David Adeang", Continent.AUSTRALIA, 2L, 21d, 14, "NR");
            CountryDto country121 = new CountryDto(121, "Nepal", "K. P. Sharma Oli", Continent.ASIA, 85L, 147516d, 7, "NP");
            CountryDto country122 = new CountryDto(122, "Netherlands", "Dick Schoof", Continent.EUROPE, 95L, 41543d, 12, "NL");
            CountryDto country123 = new CountryDto(123, "New Zealand", "Christopher Luxon", Continent.AUSTRALIA, 35L, 268838d, 16, "NZ");
            CountryDto country124 = new CountryDto(124, "Nicaragua", "Daniel Ortega", Continent.NORTH_AMERICA, 45L, 130373d, 15, "NI");
            CountryDto country125 = new CountryDto(125, "Niger", "Ali Mahaman Lamine Zeine", Continent.AFRICA, 50L, 1267000d, 8, "NE");
            CountryDto country126 = new CountryDto(126, "Nigeria", "Bola Tinubu", Continent.AFRICA, 420L, 923768d, 36, "NG");
            CountryDto country127 = new CountryDto(127, "North Korea", "Kim Tok-hun", Continent.ASIA, 140L, 120538d, 9, "KP");
            CountryDto country128 = new CountryDto(128, "North Macedonia", "Hristijan Mickoski", Continent.EUROPE, 22L, 25713d, 8, "MK");
            CountryDto country129 = new CountryDto(129, "Norway", "Jonas Gahr Støre", Continent.EUROPE, 28L, 385207d, 11, "NO");
            CountryDto country130 = new CountryDto(130, "Oman", "Haitham bin Tariq", Continent.ASIA, 110L, 309500d, 11, "OM");
            CountryDto country131 = new CountryDto(131, "Pakistan", "Shehbaz Sharif", Continent.ASIA, 480L, 881913d, 4, "PK");
            CountryDto country132 = new CountryDto(132, "Palau", "Surangel Whipps Jr.", Continent.AUSTRALIA, 5L, 459d, 16, "PW");
            CountryDto country133 = new CountryDto(133, "Palestine", "Mohammad Mustafa", Continent.ASIA, 35L, 6020d, 16, "PS");
            CountryDto country134 = new CountryDto(134, "Panama", "José Raúl Mulino", Continent.NORTH_AMERICA, 50L, 75417d, 10, "PA");
            CountryDto country135 = new CountryDto(135, "Papua New Guinea", "James Marape", Continent.AUSTRALIA, 42L, 462840d, 22, "PG");
            CountryDto country136 = new CountryDto(136, "Paraguay", "Santiago Peña", Continent.SOUTH_AMERICA, 48L, 406752d, 17, "PY");
            CountryDto country137 = new CountryDto(137, "Peru", "Eduardo Arana", Continent.SOUTH_AMERICA, 140L, 1285216d, 25, "PE");
            CountryDto country138 = new CountryDto(138, "Philippines", "Ferdinand Marcos Jr.", Continent.ASIA, 310L, 300000d, 82, "PH");
            CountryDto country139 = new CountryDto(139, "Poland", "Donald Tusk", Continent.EUROPE, 105L, 312696d, 16, "PL");
            CountryDto country140 = new CountryDto(140, "Portugal", "Luís Montenegro", Continent.EUROPE, 60L, 92090d, 18, "PT");
            CountryDto country141 = new CountryDto(141, "Qatar", "Mohammed bin Abdulrahman Al Thani", Continent.ASIA, 100L, 11586d, 8, "QA");
            CountryDto country142 = new CountryDto(142, "Romania", "Ilie Bolojan", Continent.EUROPE, 98L, 238397d, 41, "RO");
            CountryDto country143 = new CountryDto(143, "Russia", "Mikhail Mishustin", Continent.EUROPE, 700L, 17098242d, 85, "RU");
            CountryDto country144 = new CountryDto(144, "Rwanda", "Édouard Ngirente", Continent.AFRICA, 25L, 26338d, 5, "RW");
            CountryDto country145 = new CountryDto(145, "Saint Kitts and Nevis", "Terrance Drew", Continent.NORTH_AMERICA, 4L, 261d, 14, "KN");
            CountryDto country146 = new CountryDto(146, "Saint Lucia", "Philip J. Pierre", Continent.NORTH_AMERICA, 5L, 617d, 10, "LC");
            CountryDto country147 = new CountryDto(147, "Saint Vincent and the Grenadines", "Ralph Gonsalves", Continent.NORTH_AMERICA, 4L, 389d, 6, "VC");
            CountryDto country148 = new CountryDto(148, "Samoa", "Fiame Naomi Mata'afa", Continent.AUSTRALIA, 6L, 2842d, 11, "WS");
            CountryDto country149 = new CountryDto(149, "San Marino", "Alessandro Rossi", Continent.EUROPE, 3L, 61d, 9, "SM");
            CountryDto country150 = new CountryDto(150, "Sao Tome and Principe", "Américo Ramos", Continent.AFRICA, 6L, 964d, 7, "ST");
            CountryDto country151 = new CountryDto(151, "Saudi Arabia", "Mohammed bin Salman", Continent.ASIA, 350L, 2149690d, 13, "SA");
            CountryDto country152 = new CountryDto(152, "Senegal", "Ousmane Sonko", Continent.AFRICA, 70L, 196722d, 14, "SN");
            CountryDto country153 = new CountryDto(153, "Serbia", "Đuro Macut", Continent.EUROPE, 82L, 88361d, 29, "RS");
            CountryDto country154 = new CountryDto(154, "Seychelles", "Wavel Ramkalawan", Continent.AFRICA, 5L, 459d, 26, "SC");
            CountryDto country155 = new CountryDto(155, "Sierra Leone", "David Moinina Sengeh", Continent.AFRICA, 40L, 71740d, 5, "SL");
            CountryDto country156 = new CountryDto(156, "Singapore", "Lawrence Wong", Continent.ASIA, 80L, 728d, 5, "SG");
            CountryDto country157 = new CountryDto(157, "Slovakia", "Robert Fico", Continent.EUROPE, 52L, 49035d, 8, "SK");
            CountryDto country158 = new CountryDto(158, "Slovenia", "Robert Golob", Continent.EUROPE, 30L, 20273d, 12, "SI");
            CountryDto country159 = new CountryDto(159, "Solomon Islands", "Jeremiah Manele", Continent.AUSTRALIA, 8L, 28896d, 9, "SB");
            CountryDto country160 = new CountryDto(160, "Somalia", "Hamza Abdi Barre", Continent.AFRICA, 60L, 637657d, 18, "SO");
            CountryDto country161 = new CountryDto(161, "South Africa", "Cyril Ramaphosa", Continent.AFRICA, 320L, 1221037d, 9, "ZA");
            CountryDto country162 = new CountryDto(162, "South Korea", "Kim Min-seok", Continent.ASIA, 180L, 100210d, 17, "KR");
            CountryDto country163 = new CountryDto(163, "South Sudan", "Salva Kiir Mayardit", Continent.AFRICA, 45L, 619745d, 10, "SS");
            CountryDto country164 = new CountryDto(164, "Spain", "Pedro Sánchez", Continent.EUROPE, 160L, 505990d, 17, "ES");
            CountryDto country165 = new CountryDto(165, "Sri Lanka", "Harini Amarasuriya", Continent.ASIA, 90L, 65610d, 9, "LK");
            CountryDto country166 = new CountryDto(166, "Sudan", "Kamil Idris", Continent.AFRICA, 210L, 1886068d, 18, "SD");
            CountryDto country167 = new CountryDto(167, "Suriname", "Jennifer Geerlings-Simons", Continent.SOUTH_AMERICA, 15L, 163821d, 10, "SR");
            CountryDto country168 = new CountryDto(168, "Sweden", "Ulf Kristersson", Continent.EUROPE, 25L, 450295d, 21, "SE");
            CountryDto country169 = new CountryDto(169, "Switzerland", "Karin Keller-Sutter", Continent.EUROPE, 18L, 41285d, 26, "CH");
            CountryDto country170 = new CountryDto(170, "Syria", "Mohammad al-Bashir", Continent.ASIA, 160L, 185180d, 14, "SY");
            CountryDto country171 = new CountryDto(171, "Tajikistan", "Kokhir Rasulzoda", Continent.ASIA, 55L, 143100d, 2, "TJ");
            CountryDto country172 = new CountryDto(172, "Tanzania", "Kassim Majaliwa", Continent.AFRICA, 140L, 947303d, 31, "TZ");
            CountryDto country173 = new CountryDto(173, "Thailand", "Paetongtarn Shinawatra", Continent.ASIA, 210L, 513120d, 77, "TH");
            CountryDto country174 = new CountryDto(174, "Timor-Leste", "Xanana Gusmão", Continent.ASIA, 12L, 14874d, 13, "TL");
            CountryDto country175 = new CountryDto(175, "Togo", "Faure Gnassingbé", Continent.AFRICA, 25L, 56785d, 5, "TG");
            CountryDto country176 = new CountryDto(176, "Tonga", "Aisake Eke", Continent.AUSTRALIA, 3L, 747d, 5, "TO");
            CountryDto country177 = new CountryDto(177, "Trinidad and Tobago", "Kamla Persad-Bissessar", Continent.NORTH_AMERICA, 40L, 5131d, 15, "TT");
            CountryDto country178 = new CountryDto(178, "Tunisia", "Sara Zaafrani", Continent.AFRICA, 70L, 163610d, 24, "TN");
            CountryDto country179 = new CountryDto(179, "Turkey", "Recep Tayyip Erdoğan", Continent.ASIA, 320L, 783562d, 81, "TR");
            CountryDto country180 = new CountryDto(180, "Turkmenistan", "Serdar Berdimuhamedow", Continent.ASIA, 85L, 488100d, 5, "TM");
            CountryDto country181 = new CountryDto(181, "Tuvalu", "Feleti Teo", Continent.AUSTRALIA, 2L, 26d, 8, "TV");
            CountryDto country182 = new CountryDto(182, "Uganda", "Robinah Nabbanja", Continent.AFRICA, 110L, 241038d, 146, "UG");
            CountryDto country183 = new CountryDto(183, "Ukraine", "Yulia Svyrydenko", Continent.EUROPE, 180L, 603628d, 24, "UA");
            CountryDto country184 = new CountryDto(184, "United Arab Emirates", "Mohammed bin Rashid Al Maktoum", Continent.ASIA, 190L, 83600d, 7, "AE");
            CountryDto country185 = new CountryDto(185, "United Kingdom", "Keir Starmer", Continent.EUROPE, 175L, 243610d, 4, "GB");
            CountryDto country186 = new CountryDto(186, "United States", "Donald Trump", Continent.NORTH_AMERICA, 800L, 9833517d, 50, "US");
            CountryDto country187 = new CountryDto(187, "Uruguay", "Yamandú Orsi", Continent.SOUTH_AMERICA, 35L, 176215d, 19, "UY");
            CountryDto country188 = new CountryDto(188, "Uzbekistan", "Abdulla Aripov", Continent.ASIA, 120L, 448978d, 14, "UZ");
            CountryDto country189 = new CountryDto(189, "Vanuatu", "Jotham Napat", Continent.AUSTRALIA, 5L, 12189d, 6, "VU");
            CountryDto country190 = new CountryDto(190, "Vatican City", "Pope Leo XIV", Continent.EUROPE, 1L, 0.49d, 1, "VA");

            CountryDto country191 = new CountryDto(191, "Venezuela", "Nicolás Maduro", Continent.SOUTH_AMERICA, 260L, 916445d, 23, "VE");
            CountryDto country192 = new CountryDto(192, "Vietnam", "Phạm Minh Chính", Continent.ASIA, 240L, 331212d, 63, "VN");
            CountryDto country193 = new CountryDto(193, "Yemen", "Salem Saleh Bin Braik", Continent.ASIA, 170L, 527968d, 22, "YE");
            CountryDto country194 = new CountryDto(194, "Zambia", "Hakainde Hichilema", Continent.AFRICA, 65L, 752618d, 10, "ZM");
            CountryDto country195 = new CountryDto(195, "Zimbabwe", "Emmerson Mnangagwa", Continent.AFRICA, 85L, 390757d, 10, "ZW");

            List<CountryDto> countryDtos = new LinkedList<>();
            countryDtos.add(country1);
            countryDtos.add(country2);
            countryDtos.add(country3);
            countryDtos.add(country4);
            countryDtos.add(country5);
            countryDtos.add(country6);
            countryDtos.add(country7);
            countryDtos.add(country8);
            countryDtos.add(country9);
            countryDtos.add(country10);
            countryDtos.add(country11);
            countryDtos.add(country12);
            countryDtos.add(country13);
            countryDtos.add(country14);
            countryDtos.add(country15);
            countryDtos.add(country16);
            countryDtos.add(country17);
            countryDtos.add(country18);
            countryDtos.add(country19);
            countryDtos.add(country20);
            countryDtos.add(country21);
            countryDtos.add(country22);
            countryDtos.add(country23);
            countryDtos.add(country24);
            countryDtos.add(country25);
            countryDtos.add(country26);
            countryDtos.add(country27);
            countryDtos.add(country28);
            countryDtos.add(country29);
            countryDtos.add(country30);
            countryDtos.add(country31);
            countryDtos.add(country32);
            countryDtos.add(country33);
            countryDtos.add(country34);
            countryDtos.add(country35);
            countryDtos.add(country36);
            countryDtos.add(country37);
            countryDtos.add(country38);
            countryDtos.add(country39);
            countryDtos.add(country40);
            countryDtos.add(country41);
            countryDtos.add(country42);
            countryDtos.add(country43);
            countryDtos.add(country44);
            countryDtos.add(country45);
            countryDtos.add(country46);
            countryDtos.add(country47);
            countryDtos.add(country48);
            countryDtos.add(country49);
            countryDtos.add(country50);
            countryDtos.add(country51);
            countryDtos.add(country52);
            countryDtos.add(country53);
            countryDtos.add(country54);
            countryDtos.add(country55);
            countryDtos.add(country56);
            countryDtos.add(country57);
            countryDtos.add(country58);
            countryDtos.add(country59);
            countryDtos.add(country60);
            countryDtos.add(country61);
            countryDtos.add(country62);
            countryDtos.add(country63);
            countryDtos.add(country64);
            countryDtos.add(country65);
            countryDtos.add(country66);
            countryDtos.add(country67);
            countryDtos.add(country68);
            countryDtos.add(country69);
            countryDtos.add(country70);
            countryDtos.add(country71);
            countryDtos.add(country72);
            countryDtos.add(country73);
            countryDtos.add(country74);
            countryDtos.add(country75);
            countryDtos.add(country76);
            countryDtos.add(country77);
            countryDtos.add(country78);
            countryDtos.add(country79);
            countryDtos.add(country80);
            countryDtos.add(country81);
            countryDtos.add(country82);
            countryDtos.add(country83);
            countryDtos.add(country84);
            countryDtos.add(country85);
            countryDtos.add(country86);
            countryDtos.add(country87);
            countryDtos.add(country88);
            countryDtos.add(country89);
            countryDtos.add(country90);
            countryDtos.add(country91);
            countryDtos.add(country92);
            countryDtos.add(country93);
            countryDtos.add(country94);
            countryDtos.add(country95);
            countryDtos.add(country96);
            countryDtos.add(country97);
            countryDtos.add(country98);
            countryDtos.add(country99);
            countryDtos.add(country100);
            countryDtos.add(country101);
            countryDtos.add(country102);
            countryDtos.add(country103);
            countryDtos.add(country104);
            countryDtos.add(country105);
            countryDtos.add(country106);
            countryDtos.add(country107);
            countryDtos.add(country108);
            countryDtos.add(country109);
            countryDtos.add(country110);
            countryDtos.add(country111);
            countryDtos.add(country112);
            countryDtos.add(country113);
            countryDtos.add(country114);
            countryDtos.add(country115);
            countryDtos.add(country116);
            countryDtos.add(country117);
            countryDtos.add(country118);
            countryDtos.add(country119);
            countryDtos.add(country120);
            countryDtos.add(country121);
            countryDtos.add(country122);
            countryDtos.add(country123);
            countryDtos.add(country124);
            countryDtos.add(country125);
            countryDtos.add(country126);
            countryDtos.add(country127);
            countryDtos.add(country128);
            countryDtos.add(country129);
            countryDtos.add(country130);
            countryDtos.add(country131);
            countryDtos.add(country132);
            countryDtos.add(country133);
            countryDtos.add(country134);
            countryDtos.add(country135);
            countryDtos.add(country136);
            countryDtos.add(country137);
            countryDtos.add(country138);
            countryDtos.add(country139);
            countryDtos.add(country140);
            countryDtos.add(country141);
            countryDtos.add(country142);
            countryDtos.add(country143);
            countryDtos.add(country144);
            countryDtos.add(country145);
            countryDtos.add(country146);
            countryDtos.add(country147);
            countryDtos.add(country148);
            countryDtos.add(country149);
            countryDtos.add(country150);
            countryDtos.add(country151);
            countryDtos.add(country152);
            countryDtos.add(country153);
            countryDtos.add(country154);
            countryDtos.add(country155);
            countryDtos.add(country156);
            countryDtos.add(country157);
            countryDtos.add(country158);
            countryDtos.add(country159);
            countryDtos.add(country160);
            countryDtos.add(country161);
            countryDtos.add(country162);
            countryDtos.add(country163);
            countryDtos.add(country164);
            countryDtos.add(country165);
            countryDtos.add(country166);
            countryDtos.add(country167);
            countryDtos.add(country168);
            countryDtos.add(country169);
            countryDtos.add(country170);
            countryDtos.add(country171);
            countryDtos.add(country172);
            countryDtos.add(country173);
            countryDtos.add(country174);
            countryDtos.add(country175);
            countryDtos.add(country176);
            countryDtos.add(country177);
            countryDtos.add(country178);
            countryDtos.add(country179);
            countryDtos.add(country180);
            countryDtos.add(country181);
            countryDtos.add(country182);
            countryDtos.add(country183);
            countryDtos.add(country184);
            countryDtos.add(country185);
            countryDtos.add(country186);
            countryDtos.add(country187);
            countryDtos.add(country188);
            countryDtos.add(country189);
            countryDtos.add(country190);
            countryDtos.add(country191);
            countryDtos.add(country192);
            countryDtos.add(country193);
            countryDtos.add(country194);
            countryDtos.add(country195);
            for (CountryDto country : countryDtos) {
                System.out.println("["+country.getCountryId() +" = "+ country.getCountryName()+"]");
            }
        }
    }

